/**
 * Created by sunny on 2017/1/19.
 */


var template = {};

template.loginHTML = [
        "<div id='login'>",
            "<div class='login-title'>",
                "<h2>用户登录</h2>",
                "<div class='closer'>&times;</div>",
            "</div>",
            "<div class='login-body'>",
                "<div class='user-head'></div>",
                "<form action='#' method='post'>",
                    "<div class='group-container'>",
                        "<div class='input-group'>",
                            "<div class='input-group-label'>",
                                "<label for='username' id='for-username'></label>",
                            "</div>",
                            "<div class='input-group-input'>",
                                "<div class='placeholder'>用户名/手机号/邮箱</div>",
                                "<input type='text' id='username' name='username'>",
                            "</div>",
                        "</div>",
                    "</div>",
                    "<div class='group-container'>",
                        "<div class='input-group'>",
                            "<div class='input-group-label'>",
                                "<label for='password' id='for-password'></label>",
                            "</div>",
                             "<div class='input-group-input'>",
                                "<div class='placeholder'>请输入密码</div>",
                                "<input type='text' id='password' name='password'>",
                            "</div>",
                        "</div>",
                    "</div>",
                    "<div class='box-item login-options'>",
                        "<div class='checkbox-group'>",
                            "<input type='checkbox' id='rememberMe' class='checkbox-group-input'>",
                            "<label for='rememberMe' id='for-rememberMe' class='checkbox-group-label'>",
                                "<span class='outsider'></span>",
                                "<span class='insider'></span>",
                                "<span class='txt'>7天内记住我</span>",
                            "</label>",
                        "</div>",
                        "<a href='#' id='forgotPassword'>忘记密码</a>",
                        "<a href='#' id='toRegister'>注册账号</a>",
                    "</div>",
                    "<label for='loginSubmit' id='for-loginSubmit'>登 录</label>",
                    "<input type='submit' id='loginSubmit'>",
                "</form>",
            "</div>",
        "</div>",
    "</div>"
].join("");

template.registerHTML = [
    "<div id='register'>",
    "<div class='register-title'>",
    "<h2>用户注册</h2>",
    "<div class='closer'>&times;</div>",
    "</div>",
    "<div class='register-body'>",
    "<div class='info-panel'>",
    "<form action='#' method='post'>",
    "<div class='group-container'>",
    "<div class='input-group'>",
    "<div class='input-group-label'>",
    "<label for='username'  class='label'>用户名</label>",
    "</div>",
    "<div class='input-group-input'>",
    "<div class='placeholder'>请输入用户名</div>",
    "<input type='text' id='username' name='username' title='用户名必须由字母、下划线、数字组成，长度最小6位最长19位，不区分大小写'>",
    "</div>",
    "<div class='input-group-verify'>",
    "<div class='verify-right'></div>",
    "<div class='verify-error'></div>",
    "</div>",
    "</div>",
    "<div class='tips'>用户名必须由字母、下划线、数字组成，长度最小6位最大19位，不区分大小写</div>",
    "</div>",
    "<div class='group-container'>",
    "<div class='input-group'>",
    "<div class='input-group-label'>",
    "<label for='password' class='label'>设置密码</label>",
    "</div>",
    "<div class='input-group-input'>",
    "<div class='placeholder'>请设置您的登录密码</div>",
    "<input type='text' id='password' name='password'>",
    "</div>",
    "<div class='input-group-verify'>",
    "<div class='verify-right'></div>",
    "<div class='verify-error'></div>",
    "</div>",
    "</div>",
    "<div class='tips'>密码长度最小8位最大50位，区分大小写</div>",
    "</div>",
    "<div class='group-container'>",
    "<div class='input-group'>",
    "<div class='input-group-label'>",
    "<label for='repassword'>确认密码</label>",
    "</div>",
    "<div class='input-group-input'>",
    "<div class='placeholder'>请设再次输入密码</div>",
    "<input type='text' id='repassword' name='repassword'>",
    "</div>",
    "<div class='input-group-verify'>",
    "<div class='verify-right'></div>",
    "<div class='verify-error'></div>",
    "</div>",
    "</div>",
    "</div>",
    "<div class='verify-box'>",
    "<div class='group-container'>",
    "<div class='input-group'>",
    "<div class='input-group-label'>",
    "<label for='verifyCode'  class='label'>验证码</label>",
    "</div>",
    "<div class='input-group-input'>",
    "<div class='placeholder'>请输入验证码</div>",
    "<input type='text' id='verifyCode' name='verifyCode'>",
    "</div>",
    "<div class='input-group-verify'>",
    "<div class='verify-right'></div>",
    "<div class='verify-error'></div>",
    "</div>",
    "</div>",
    "</div>",
    "<div class='verifyImg-box'>",
    "<img src='' alt='验证码' id='verifyImg'>",
    "<a href='#' id='refresh-btn'></a>",
    "</div>",
    "</div>",
    "<label for='register-btn' id='registerBtn'>立即注册</label>",
    "<input type='submit' id='register-btn' style='display: none'>",
    "</form>",
    "</div>",
    "</div>"
].join("");
